"""Generate the native English catalog from the shared UI translations."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
messages = json.loads((root / 'src/locales/en.json').read_text())
def swift(value):
    return json.dumps(value, ensure_ascii=False)
output = '// Generated by scripts/generate-localizations.py. Edit src/locales/en.json.\n'
output += 'let englishMessages: [String: String] = [\n'
output += ''.join(f'    {swift(key)}: {swift(value)},\n' for key, value in sorted(messages.items()))
output += ']\n'
(root / 'ios/VibeWord/Core/EnglishMessages.swift').write_text(output)
